"""
Translation strings for the dashboard
"""

TRANSLATIONS = {
    "de": {
        # Welcome Page
        "welcome_title": "Dashboard",
        "welcome_subtitle": "Test",
        "welcome_greeting": "Willkommen!",
        "welcome_description": "Dieses Dashboard bietet umfassende Einblicke in die Nutzung deiner Lernplattform.",
        "tip": "Tipp: Verwende das Seitenmenü, um zwischen verschiedenen Ansichten zu navigieren!",
        "last_updated": "Zuletzt aktualisiert: Februar 2026 | Daten sind in Echtzeit",
        
        # Overview Page
        "overview_title": "Dashboard Übersicht",
        "time_periods": "📅 Zeitraumfilter",
        "last_day": "Letzter Tag",
        "last_week": "Letzte Woche",
        "last_month": "Letzter Monat",
        "last_3_months": "Letzte 3 Monate",
        "last_6_months": "Letzte 6 Monate",
        "total_questions": "📝 Gesamtzahl Fragen",
        "questions_metric": "Gesamtzahl der Fragen, die Benutzer im ausgewählten Zeitraum gestellt haben.",
        "total_sessions": "👥 Sitzungen",
        "sessions_metric": "Anzahl der eindeutigen Benutzersitzungen innerhalb des ausgewählten Zeitraums. Eine Sitzung stellt die kontinuierliche Interaktion eines Benutzers mit der Plattform dar.",
        "avg_response": "⌛ Durchschn. Antwort",
        "response_length_metric": "Durchschnittliche Länge der vom Modell generierten Antworten. Gemessen in Zeichen, gibt diese Metrik die Detailliertheit und Tiefe der Antworten an.",
        "avg_query": "❓ Durchschn. Anfrage",
        "avg_query_metric": "Durchschnittliche Länge der von Benutzern gestellten Fragen in Zeichen.",
        "questions_over_time": "Fragen im Zeitverlauf",
        "daily_volume": "Tägliches Frageaufkommen",
        "date": "Datum",
        "number_of_questions": "Anzahl der Fragen",
        "hourly_activity": "Stündliche Aktivität",
        "hour_utc": "Stunde",
        
        # Session Explorer
        "sort_by": "Sortieren nach",
        "newest_first": "Neueste zuerst",
        "oldest_first": "Älteste zuerst",
        "most_messages": "Meiste Nachrichten",
        "least_messages": "Wenigste Nachrichten",
        "no_sessions_found": "Keine Sitzungen gefunden",
        "messages": "Nachrichten",
        "model": "Modell",
        "duration": "Dauer",
        "question_answer_pairs": "Frage-Antwort-Paare:",
        "getting_started": "Erste Schritte",
        "navigate_to": "Navigiere zu:",
        "overview": "Übersicht",
        "session_explorer": "Sitzungsübersicht",
    },
    "en": {
        # Welcome Page
        "welcome_title": "Dashboard",
        "welcome_subtitle": "Test",
        "welcome_greeting": "Welcome!",
        "welcome_description": "This dashboard provides comprehensive insights into your LLM learning platform usage.",
        "tip": "Tip: Use the sidebar menu to navigate between different views!",
        "last_updated": "Last updated: February 2026 | Data is real-time",
        
        # Overview Page
        "overview_title": "Dashboard Overview",
        "time_periods": "📅 Time Period Filters",
        "last_day": "Last Day",
        "last_week": "Last Week",
        "last_month": "Last Month",
        "last_3_months": "Last 3 Months",
        "last_6_months": "Last 6 Months",
        "total_questions": "📝 Total Questions",
        "questions_metric": "Total number of questions asked by users in the selected time period. This is a key indicator of platform engagement.",
        "total_sessions": "👥 Sessions",
        "sessions_metric": "Number of unique user sessions within the selected time period. A session represents one user's continuous interaction with the platform.",
        "avg_response": "⌛ Avg Response",
        "response_length_metric": "Average length of responses generated by the model. Measured in characters, this metric indicates response detail and depth.",
        "avg_query": "❓ Avg Query",
        "avg_query_metric": "Average length of questions asked by users in characters.",
        "questions_over_time": "Questions Over Time",
        "daily_volume": "Daily Question Volume",
        "date": "Date",
        "number_of_questions": "Number of Questions",
        "hourly_activity": "Hourly Activity",
        "hour_utc": "Hour",
        
        # Session Explorer
        "sort_by": "Sort by",
        "newest_first": "Newest first",
        "oldest_first": "Oldest first",
        "most_messages": "Most messages",
        "least_messages": "Least messages",
        "no_sessions_found": "No sessions found",
        "messages": "Messages",
        "model": "Model",
        "duration": "Duration",
        "question_answer_pairs": "Question-Answer Pairs:",
        "getting_started": "Getting Started",
        "navigate_to": "Navigate to:",
        "overview": "Overview",
        "session_explorer": "Session Explorer",
    }
}

def get_text(key, language="de"):
    """Get translated text for a key"""
    return TRANSLATIONS.get(language, {}).get(key, key)

def init_language():
    """Initialize language in session state"""
    if "language" not in st.session_state:
        st.session_state.language = "de"
    return st.session_state.language

# Need to import streamlit for init_language
import streamlit as st
